
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: cimg/go:1.13

    working_directory: ~/go/src/github.com/{{ORG_NAME}}/configurations
    steps:
      - checkout
      - setup_remote_docker
      #- run:
      #    name: Install Docker client
      #    command: apk add docker-cli
      - run: |
          docker login -u $DOCKERREPO_USER -p $DOCKERREPO_PASSWORD cloud.canister.io:5000
          make build && make docker && make publish
      - run: make test
    
