
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: cimg/go:1.13
        auth:
          username: bastiao
          password: $DOCKERREPO_PASSWORD 

    working_directory: ~/go/src/github.com/{{ORG_NAME}}/configurations
    steps:
      - checkout
      - setup_remote_docker:
        docker_layer_caching: true

      # specify any bash command here prefixed with `run: `
      - run:
        name: Install Docker client
        command: apk add docker-cli
      - run: make build && make docker
      - run: make test
