phabricator:
    endpoint: https://domain.example
    token: cli-34567890
    repo: repo01 #example

jenkins:
    endpoint: https://ci-jenkins
    username: example
    token: 34567890
    pipeline: "testingJenkins" # Pipeline by default 
